.include "m328pdef.inc"

.EQU Vec1 = 0x0140;POSICION DE MEMORIA DONDE BUSCO GUARDAR LA TABLA
.EQU Vec2 = 0x0500;POSICION DE MEMORIA DONDE QUIERO GUARDAR LA TABLA
.EQU cant_nros = 6;CANTIDAD DE NUMEROS EN LA TABLA PARA ORDENAR

.CSEG
	RJMP MAIN

.ORG INT_VECTORS_SIZE

MAIN:
;INICIALIZO STACK
	LDI R16,HIGH(RAMEND)
	OUT SPH,R16
	LDI R16,LOW(RAMEND)
	OUT SPL,R16
;[FIN]INICIALIZO STACK

	RJMP ORDENAR
	RJMP GUARDAR

HERE: RJMP HERE

ORDENAR:
	LDI ZH,HIGH(TABLA<<1);CARGO A PUNTERO Z CON DIRECCION DE MEMORIA DE LA TABLA
	LDI ZL,LOW(TABLA<<1);CARGO A PUNTERO Z CON DIRECCION DE MEMORIA DE LA TABLA
	LDI R16,cant_nros;GUARDO EN R16 LA CANTIDAD DE NUMEROS A ORDENAR
	LDI R17,cant_nros-1;GUARDO EN R17 LA CANTIDAD DE NUMEROS A COMPARAR CON LA POSICION A LLENAR
	LPM R20,Z+;GUARDO EN R20 EL NUMERO A COMPARAR CON EL RESTO
	LDI R14,HIGH(Vec1);GUARDO EN R14 EL BYTE SUPERIOR DE LA POSICION A LLENAR
	LDI R15,LOW(Vec1);GUARDO EN R15 EL BYTE INFERIOR DE LA POSICION A LLENAR

COMPARAR:
	LPM R21,Z+;GUARDO EN R21 EL NUMERO TEMPORARIO A COMPARAR CON EL ACTUAL (QUE ESTA EN R20)
	CP R20,R21;COMPARO EL SUPUESTO MAYOR NUMERO (R20) CON EL POSIBLE MAYOR NUMERO (R21)
	BRLO INTERCAMBIAR;SI EL NUMERO SUPUESTAMENTE MAYOR (R20) ES MENOR QUE EL OTRO (R21), SE PROCEDE A CAMBIAR EL NUMERO A COMPARAR
	DEC R17;BAJO EN 1 LOS NUMEROS A COMPARAR CON EL ACTUAL
	BRNE AVANZAR_POSICION;SI YA ME QUEDE SIN NUMEROS EN LA TABLA PARA COMPARAR, PROCEDO A LLENAR LA SIGUIENTE POSICION
	RJMP COMPARAR;VUELVO A COMENZAR EL PROCESO DE COMPARACION

INTERCAMBIAR:
	ST -Z,R20;CARGO EN ESTA POSICION DE LA TABLA EL ANTERIOR NUMERO MAYOR A COMPARAR
	MOV R18,R30;GUARDO EN R18 EL BYTE SUPERIOR DE LA POSICION EN LA TABLA EN LA QUE TENGO QUE SEGUIR LEYENDO
	MOV R19,R31;GUARDO EN R19 EL BYTE INFERIOR DE LA POSICION EN LA TABLA EN LA QUE TENGO QUE SEGUIR LEYENDO
	MOV ZH,R14;CARGO EN EL BYTE SUPERIOR DE Z (GUARDADO EN R14) LA POSICION DONDE TENGO QUE REEMPLAZAR AL NUEVO NUMERO MAYOR
	MOV ZL,R15;CARGO EN EL BYTE INFERIOR DE Z (GUARDADO EN R15) LA POSICION DONDE TENGO QUE REEMPLAZAR AL NUEVO NUMERO MAYOR
	ST Z,R21;GUARDO EN LA POSICION DE LA TABLA CORRESPONDIENTE EL NUEVO NUMERO MAYOR PARA ESTA POSICION
	MOV R20,R21;GUARDO EL NUEVO NUEVO MAYOR A COMPARAR EN R20
	MOV ZH,R18;CARGO EN EL BYTE SUPERIOR DE Z LA POSICION PARA CONTINUAR LEYENDO
	MOV ZL,R19;CARGO EN EL BYTE INFERIOR DE Z LA POSICION PARA CONTINUAR LEYENDO

AVANZAR_POSICION:
	INC R15;AUMENTO EN UNO LA POSICION DE LA TABLA DONDE HAY QUE CONTINUAR LEYENDO (R15 = BYTE INFERIOR)
	CLR R18;LIMPIO EL REGISTRO R18 PARA TENER UN VALOR EN 0
	ADC R14,R18;SI R15 = FF, ENTONCES TENGO EN UNO EL CARRY Y DEBO SUMARLE UNO AL BYTE SUPERIOR EN R14
	MOV ZH,R14;CARGO EN Z LA POSICION PARA SEGUIR LEYENDO (BYTE SUPERIOR)
	MOV ZL,R15;CARGO EN Z LA POSICION PARA SEGUIR LEYENDO (BYTE INFERIOR)
	LPM R20,Z+;GUARDO EN R20 EL NUMERO A COMPARAR CON EL RESTO
	DEC R16;BAJO EN UNO LA CANTIDAD DE NUMEROS DE LA TABLA QUE ME QUEDAN LLENAR
	MOV R16,R17;ACTUALIZO LA CANTIDAD DE NUMEROS A COMPARAR CON LA POSICION ACTUAL
	DEC R17;BAJO EN UNO LA CANTIDAD DE NUMEROS A COMPARAR YA QUE DEBO COMPARAR LOS QUE QUEDAN CON EL FIJO
	BRNE COMPARAR;SI TENGO NUMEROS PARA COMPARAR, VUELVO A LA ETIQUETA QUE ME PERMITE HACERLO
RET;SI NO ME QUEDAN NUMEROS PARA COMPARAR, DOY POR FINALIZADO LA TAREA DE ORDENAMIENTO DE LA TABLA

GUARDAR:
	LDI ZH,HIGH(TABLA<<1);CARGO A PUNTERO Z CON DIRECCION DE INICIO DE LA TABLA (BYTE SUPERIOR)
	LDI ZL,LOW(TABLA<<1);CARGO A PUNTERO Z CON DIRECCION DE INICIO DE LA TABLA (BYTE INFERIOR)
	LDI XH,HIGH(Vec2<<1);CARGO A PUNTERO X CON DIRECCION DE INICIO DE LA TABLA A LLENAR (BYTE SUPERIOR)
	LDI XL,LOW(Vec2<<1);CARGO A PUNTERO X CON DIRECCION DE INICIO DE LA TABLA A LLENAR (BYTE INFERIOR)
	LDI R15,cant_nros;GUARDO EN R15 LA CANTIDAD DE NUMEROS A CARGAR PARA LLEVAR UN SEGUIMIENTO

LLENAR_SEGUNDA_TABLA:
	LPM R16,Z+;GUARDO EN EL REGISTRO R16 EL NUMERO ACTUAL A CARGAR EN LA NUEVA TABLA Y ME MUEVO UNA POSICION EN LA TABLA LLENA
	ST X+,R16;GUARDO EN EL REGISTRO R16 EL NUMERO ACTUAL EN LA NUEVA TABLA Y ME MUEVO UNA POSICION EN LA TABLA A LLENAR
	DEC R15;BAJO EN UNO LA CANTIDAD DE NUMEROS A LLENAR
	BRNE LLENAR_SEGUNDA_TABLA;SI NO ES 0 LA CANTIDAD DE NUMEROS A LLENAR, CONTINUO CON EL PROCESO
RET;SI YA TERMINE DE PASAR TODOS LOS NUMEROS, DOY POR FINALIZADO EL PROCESO

.ORG Vec1
TABLA:.DB 0x01,0x05,0x06,0x08,0x02,0x07;TABLA DE NUMEROS A LLENAR
